In [1]:
# imports and env't config 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.gridspec as gridspec
import json
import requests 
from imp import reload 
import Util; reload(Util)
import warnings
import time 
import Cdf
import Pmf
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
# read  
webget_2016 = pd.read_csv("../dataset/webget_2016.csv", sep = ',', encoding = "ISO-8859-1")
webget_df_2016 = webget_2016[webget_2016['dtime'] <= '2017-07-01']
webget_df_2016 = webget_df_2016[webget_df_2016['ttfb_avg'] > 0]

In [3]:
webget_df_2016 = webget_df_2016[webget_2016['country'] != '']
webget_df_2016 = webget_df_2016.dropna(subset=['country'])
webget_df_2016['fetch_time'] = webget_df_2016['fetch_time'].div(1000)
webget_df_2016['ttfb_avg'] = webget_df_2016['ttfb_avg'].div(1000)
webget_df_2016['lookup_avg_time'] = webget_df_2016['lookup_avg_time'].div(1000)

google_16 = webget_df_2016[webget_df_2016['target'].str.contains("google.com")]
facebook_16 = webget_df_2016[webget_df_2016['target'].str.contains("facebook.com")]
youtube_16 = webget_df_2016[webget_df_2016['target'].str.contains("youtube.com")]

In [4]:
eu_1 = ['Belgium', 'France', 'Italy', 'Spain', 'Germany', 'Romania', 'Latvia', \
        'Netherlands' , 'Switzerland', 'Czechia', 'Finland', 'Norway', 'Sweden', \
        'United Kingdom', 'Ireland', 'Slovenia','Israel', 'Bosnia and Herzegovina']
# eu_2 = ['Finland', 'Norway', 'Sweden', 'United Kingdom', 'Ireland', 'Slovenia']
us_ca = ['United States', 'Canada']
others = ['South Africa', 'Philippines', 'Singapore', 'New Zealand', 'Japan',  \
          'Brazil',  'Australia']

In [5]:
fb_eu = facebook_16[facebook_16['country'].isin(eu_1)]
fb_us_ca = facebook_16[facebook_16['country'].isin(us_ca)]
fb_others = facebook_16[facebook_16['country'].isin(others)]

ggl_eu = google_16[google_16['country'].isin(eu_1)]
ggl_us_ca = google_16[google_16['country'].isin(us_ca)]
ggl_others = google_16[google_16['country'].isin(others)]

ut_eu = youtube_16[youtube_16['country'].isin(eu_1)]
ut_us_ca = youtube_16[youtube_16['country'].isin(us_ca)]
ut_others = youtube_16[youtube_16['country'].isin(others)]

In [6]:
fb_eu_ttfb = fb_eu['ttfb_avg'] 
fb_us_ca_ttfb = fb_us_ca['ttfb_avg'] 
fb_others_ttfb = fb_others['ttfb_avg']

In [7]:
# CDF for ASes that have more than 10 probes 
TI = 3269
CC = 7922
BT = 2856

fb_bt = facebook_16[facebook_16['asn'] == BT]
fb_cc = facebook_16[facebook_16['asn'] == CC]
fb_ti = facebook_16[facebook_16['asn'] == TI]

ggl_bt = google_16[google_16['asn'] == BT]
ggl_cc = google_16[google_16['asn'] == CC]
ggl_ti = google_16[google_16['asn'] == TI]

ut_bt = youtube_16[youtube_16['asn'] == BT]
ut_cc = youtube_16[youtube_16['asn'] == CC]
ut_ti = youtube_16[youtube_16['asn'] == TI]

In [8]:
# op-webpage-TTFB 
bt_f_ttfb = fb_bt['ttfb_avg']
bt_g_ttfb = ggl_bt['ttfb_avg']
bt_u_ttfb = ut_bt['ttfb_avg']

cc_f_ttfb = fb_cc['ttfb_avg']
cc_g_ttfb = ggl_cc['ttfb_avg']
cc_u_ttfb = ut_cc['ttfb_avg']

ti_f_ttfb = fb_ti['ttfb_avg']
ti_g_ttfb = ggl_ti['ttfb_avg']
ti_u_ttfb = ut_ti['ttfb_avg'] 

# op-webpage-download time 
bt_f_dt = fb_bt['fetch_time']
bt_g_dt = ggl_bt['fetch_time']
bt_u_dt = ut_bt['fetch_time']

cc_f_dt = fb_cc['fetch_time']
cc_g_dt = ggl_cc['fetch_time']
cc_u_dt = ut_cc['fetch_time']

ti_f_dt = fb_ti['fetch_time']
ti_g_dt = ggl_ti['fetch_time']
ti_u_dt = ut_ti['fetch_time']

## Basic Statistics

In [9]:
bt_f_ttfb_l = bt_f_ttfb.describe().tolist()
ti_f_ttfb_l = ti_f_ttfb.describe().tolist()
cc_f_ttfb_l = cc_f_ttfb.describe().tolist()

bt_g_ttfb_l = bt_g_ttfb.describe().tolist()
ti_g_ttfb_l = ti_g_ttfb.describe().tolist()
cc_g_ttfb_l = cc_g_ttfb.describe().tolist()

bt_u_ttfb_l = bt_u_ttfb.describe().tolist()
ti_u_ttfb_l = ti_u_ttfb.describe().tolist()
cc_u_ttfb_l = cc_u_ttfb.describe().tolist()

bt_f_dt_l = bt_f_dt.describe().tolist()
ti_f_dt_l = ti_f_dt.describe().tolist()
cc_f_dt_l = cc_f_dt.describe().tolist()

bt_g_dt_l = bt_g_dt.describe().tolist()
ti_g_dt_l = ti_g_dt.describe().tolist()
cc_g_dt_l = cc_g_dt.describe().tolist()

bt_u_dt_l = bt_u_dt.describe().tolist()
ti_u_dt_l = ti_u_dt.describe().tolist()
cc_u_dt_l = cc_u_dt.describe().tolist()

In [10]:
cols = bt_f_ttfb.describe().index.tolist()

In [11]:
df_stat_op = pd.DataFrame({
    'BT_F_TTFB': bt_f_ttfb_l,'TI_F_TTFB': ti_f_ttfb_l,'CC_F_TTFB': cc_f_ttfb_l,
    'BT_G_TTFB': bt_g_ttfb_l,'TI_G_TTFB': ti_g_ttfb_l,'CC_G_TTFB': cc_g_ttfb_l,
    'BT_U_TTFB': bt_u_ttfb_l,'TI_U_TTFB': ti_u_ttfb_l,'CC_U_TTFB': cc_u_ttfb_l,
    'BT_F_dt': bt_f_dt_l,'TI_F_dt': ti_f_dt_l,'CC_F_dt': cc_f_dt_l,
    'BT_G_dt': bt_g_dt_l,'TI_G_dt': ti_g_dt_l,'CC_G_dt': cc_g_dt_l,
    'BT_U_dt': bt_u_dt_l,'TI_U_dt': ti_u_dt_l,'CC_U_dt': cc_u_dt_l,
})
df_stat_by_operator = df_stat_op.T
df_stat_by_operator.columns = cols
df_stat_by_operator[['count', 'min', 'mean', 'std', '50%', '75%', 'max']].round(2)

             count     min     mean      std     50%     75%       max
BT_F_TTFB  88463.0    1.61   152.14   183.93  114.07  153.88   9719.73
TI_F_TTFB  81740.0   10.52   148.73   101.94  135.33  165.33   5847.50
CC_F_TTFB  75547.0   23.78   202.19   188.24  120.75  233.49  13049.29
BT_G_TTFB  88459.0    1.64   107.79   258.14   40.55  101.23   6601.64
TI_G_TTFB  81625.0   11.12    88.81   103.32   69.96   95.69   7732.91
CC_G_TTFB  77638.0   25.12    74.76    72.34   67.06   86.14   6384.97
BT_U_TTFB  88460.0    1.47   158.29   216.93  100.55  153.24   4892.89
TI_U_TTFB  81750.0   10.60   140.06    91.00  118.91  147.72   8621.42
CC_U_TTFB  77629.0   27.23   100.73    76.95   79.00  138.53   4401.78
BT_F_dt    88463.0    4.50  1182.46  4566.06  384.87  557.13  54448.19
TI_F_dt    81740.0   23.90   562.91   564.26  488.55  584.36  30164.50
CC_F_dt    75547.0   49.38   640.88   624.26  459.36  882.89  48170.59
BT_G_dt    88459.0    4.42  1632.93  6098.13  334.96  730.06  57590.21
TI_G_dt    81625.0   23.74   785.90  1177.10  511.43  725.00  48321.89
CC_G_dt    77638.0  203.71   500.45   559.39  437.91  540.29  60210.99
BT_U_dt    88460.0    4.21  1570.99  4850.04  474.96  947.01  49226.16
TI_U_dt    81750.0   24.70   915.79   920.06  642.14  935.12  42810.86
CC_U_dt    77629.0  277.34   607.58   582.20  536.89  660.76  30582.90

In [12]:
# by region 
eu_f_ttfb = fb_eu['ttfb_avg'] 
us_ca_f_ttfb = fb_us_ca['ttfb_avg'] 
others_f_ttfb = fb_others['ttfb_avg'] 

eu_g_ttfb = ggl_eu['ttfb_avg'] 
us_ca_g_ttfb = ggl_us_ca['ttfb_avg'] 
others_g_ttfb = ggl_others['ttfb_avg'] 

eu_u_ttfb = ut_eu['ttfb_avg'] 
us_ca_u_ttfb = ut_us_ca['ttfb_avg'] 
others_u_ttfb = ut_others['ttfb_avg'] 

eu_f_dt = fb_eu['fetch_time']
eu_g_dt = ggl_eu['fetch_time']
eu_u_dt = ut_eu['fetch_time']

us_ca_f_dt = fb_us_ca['fetch_time']
us_ca_g_dt = ggl_us_ca['fetch_time']
us_ca_u_dt = ut_us_ca['fetch_time']

others_f_dt = fb_others['fetch_time']
others_g_dt = ggl_others['fetch_time']
others_u_dt = ut_others['fetch_time']

In [13]:
eu_f_ttfb_l = eu_f_ttfb.describe().tolist()
us_ca_f_ttfb_l = us_ca_f_ttfb.describe().tolist()
others_f_ttfb_l = others_f_ttfb.describe().tolist()

eu_g_ttfb_l = eu_g_ttfb.describe().tolist()
us_ca_g_ttfb_l = us_ca_g_ttfb.describe().tolist()
others_g_ttfb_l = others_g_ttfb.describe().tolist()

eu_u_ttfb_l = eu_u_ttfb.describe().tolist()
us_ca_u_ttfb_l = us_ca_u_ttfb.describe().tolist()
others_u_ttfb_l = others_u_ttfb.describe().tolist()

eu_f_dt_l = eu_f_dt.describe().tolist()
us_ca_f_dt_l = us_ca_f_dt.describe().tolist()
others_f_dt_l = others_f_dt.describe().tolist()

eu_g_dt_l = eu_g_dt.describe().tolist()
us_ca_g_dt_l = us_ca_g_dt.describe().tolist()
others_g_dt_l = others_g_dt.describe().tolist()

eu_u_dt_l = eu_u_dt.describe().tolist()
us_ca_u_dt_l = us_ca_u_dt.describe().tolist()
others_u_dt_l = others_u_dt.describe().tolist()

In [14]:
df_stat_reg = pd.DataFrame({
    'eu_F_TTFB': eu_f_ttfb_l,'us_ca_F_TTFB': us_ca_f_ttfb_l,'others_F_TTFB': others_f_ttfb_l,
    'eu_G_TTFB': eu_g_ttfb_l,'us_ca_G_TTFB': us_ca_g_ttfb_l,'others_G_TTFB': others_g_ttfb_l,
    'eu_U_TTFB': eu_u_ttfb_l,'us_ca_U_TTFB': us_ca_u_ttfb_l,'others_U_TTFB': others_u_ttfb_l,
    'eu_F_dt': eu_f_dt_l,'us_ca_F_dt': us_ca_f_dt_l,'others_F_dt': others_f_dt_l,
    'eu_G_dt': eu_g_dt_l,'us_ca_G_dt': us_ca_g_dt_l,'others_G_dt': others_g_dt_l,
    'eu_U_dt': eu_u_dt_l,'us_ca_U_dt': us_ca_u_dt_l,'others_U_dt': others_u_dt_l,
})
df_stat_by_region = df_stat_reg.T
df_stat_by_region.columns = cols
df_stat_by_region = df_stat_by_region[['min', 'mean', 'std', '50%', '75%', 'max']].round(2)

## Prepare for latex table  use  by  region

In [15]:
## Facebook 
print("\t\multirow{2}{*}{FB} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_region['50%']['eu_F_TTFB'],
                                                  df_stat_by_region['75%']['eu_F_TTFB'],
                                                  df_stat_by_region['mean']['eu_F_TTFB'],
                                                  df_stat_by_region['50%']['us_ca_F_TTFB'],
                                                  df_stat_by_region['75%']['us_ca_F_TTFB'],
                                                  df_stat_by_region['mean']['us_ca_F_TTFB'],
                                                  df_stat_by_region['50%']['others_F_TTFB'],
                                                  df_stat_by_region['75%']['others_F_TTFB'],
                                                  df_stat_by_region['mean']['others_F_TTFB']))

print(" \t \t & DwnT & %.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_region['50%']['eu_F_dt'],
                                                  df_stat_by_region['75%']['eu_F_dt'], 
                                                  df_stat_by_region['mean']['eu_F_dt'],
                                                  df_stat_by_region['50%']['us_ca_F_dt'],
                                                  df_stat_by_region['75%']['us_ca_F_dt'],
                                                  df_stat_by_region['mean']['us_ca_F_dt'],
                                                  df_stat_by_region['50%']['others_F_dt'],
                                                  df_stat_by_region['75%']['others_F_dt'],
                                                  df_stat_by_region['mean']['others_F_dt']))

	\multirow{2}{*}{FB} & TTFB & 153 & 319 & 222 & 141 & 228 & 209 & 540 & 858 & 626 \\
 	 	 & DwnT & 536 & 1000& 962 & 523 & 829 & 654 & 2286 & 4244 & 3244 \\

In [16]:
## Google 
print("\t\multirow{2}{*}{GGL} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_region['50%']['eu_G_TTFB'],
                                                  df_stat_by_region['75%']['eu_G_TTFB'],
                                                  df_stat_by_region['mean']['eu_G_TTFB'],
                                                  df_stat_by_region['50%']['us_ca_G_TTFB'],
                                                  df_stat_by_region['75%']['us_ca_G_TTFB'],
                                                  df_stat_by_region['mean']['us_ca_G_TTFB'],
                                                  df_stat_by_region['50%']['others_G_TTFB'],
                                                  df_stat_by_region['75%']['others_G_TTFB'],
                                                  df_stat_by_region['mean']['others_G_TTFB']))

print(" \t \t & DwnT & %.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_region['50%']['eu_G_dt'],
                                                  df_stat_by_region['75%']['eu_G_dt'], 
                                                  df_stat_by_region['mean']['eu_G_dt'],
                                                  df_stat_by_region['50%']['us_ca_G_dt'],
                                                  df_stat_by_region['75%']['us_ca_G_dt'],
                                                  df_stat_by_region['mean']['us_ca_G_dt'],
                                                  df_stat_by_region['50%']['others_G_dt'],
                                                  df_stat_by_region['75%']['others_G_dt'],
                                                  df_stat_by_region['mean']['others_G_dt']))

	\multirow{2}{*}{GGL} & TTFB & 55 & 86 & 78 & 70 & 99 & 93 & 191 & 238 & 177 \\
 	 	 & DwnT & 394 & 610& 808 & 460 & 647 & 645 & 1407 & 1788 & 1610 \\

In [17]:
## YouTube 
print("\t\multirow{2}{*}{YT} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_region['50%']['eu_U_TTFB'],
                                                  df_stat_by_region['75%']['eu_U_TTFB'],
                                                  df_stat_by_region['mean']['eu_U_TTFB'],
                                                  df_stat_by_region['50%']['us_ca_U_TTFB'],
                                                  df_stat_by_region['75%']['us_ca_U_TTFB'],
                                                  df_stat_by_region['mean']['us_ca_U_TTFB'],
                                                  df_stat_by_region['50%']['others_U_TTFB'],
                                                  df_stat_by_region['75%']['others_U_TTFB'],
                                                  df_stat_by_region['mean']['others_U_TTFB']))

print(" \t \t & DwnT & %.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_region['50%']['eu_U_dt'],
                                                  df_stat_by_region['75%']['eu_U_dt'], 
                                                  df_stat_by_region['mean']['eu_U_dt'],
                                                  df_stat_by_region['50%']['us_ca_U_dt'],
                                                  df_stat_by_region['75%']['us_ca_U_dt'],
                                                  df_stat_by_region['mean']['us_ca_U_dt'],
                                                  df_stat_by_region['50%']['others_U_dt'],
                                                  df_stat_by_region['75%']['others_U_dt'],
                                                  df_stat_by_region['mean']['others_U_dt']))

	\multirow{2}{*}{YT} & TTFB & 117 & 151 & 142 & 82 & 144 & 118 & 230 & 302 & 253 \\
 	 	 & DwnT & 595 & 864& 958 & 585 & 735 & 743 & 1722 & 2359 & 2068 \\

## Prepare for latex table  use  by  operator

In [18]:
## Facebook 
print("\t\multirow{2}{*}{FB} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_operator['50%']['BT_F_TTFB'],
                                                  df_stat_by_operator['75%']['BT_F_TTFB'],
                                                  df_stat_by_operator['mean']['BT_F_TTFB'],
                                                  df_stat_by_operator['50%']['CC_F_TTFB'],
                                                  df_stat_by_operator['75%']['CC_F_TTFB'],
                                                  df_stat_by_operator['mean']['CC_F_TTFB'],
                                                  df_stat_by_operator['50%']['TI_F_TTFB'],
                                                  df_stat_by_operator['75%']['TI_F_TTFB'],
                                                  df_stat_by_operator['mean']['TI_F_TTFB']))

print(" \t \t & DwnT & %.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_operator['50%']['BT_F_dt'],
                                                  df_stat_by_operator['75%']['BT_F_dt'], 
                                                  df_stat_by_operator['mean']['BT_F_dt'],
                                                  df_stat_by_operator['50%']['CC_F_dt'],
                                                  df_stat_by_operator['75%']['CC_F_dt'],
                                                  df_stat_by_operator['mean']['CC_F_dt'],
                                                  df_stat_by_operator['50%']['TI_F_dt'],
                                                  df_stat_by_operator['75%']['TI_F_dt'],
                                                  df_stat_by_operator['mean']['TI_F_dt']))

	\multirow{2}{*}{FB} & TTFB & 114 & 154 & 152 & 121 & 233 & 202 & 135 & 165 & 149 \\
 	 	 & DwnT & 385 & 557& 1182 & 459 & 883 & 641 & 489 & 584 & 563 \\

In [19]:
## Google 
print("\t\multirow{2}{*}{GGL} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_operator['50%']['BT_G_TTFB'],
                                                  df_stat_by_operator['75%']['BT_G_TTFB'],
                                                  df_stat_by_operator['mean']['BT_G_TTFB'],
                                                  df_stat_by_operator['50%']['CC_G_TTFB'],
                                                  df_stat_by_operator['75%']['CC_G_TTFB'],
                                                  df_stat_by_operator['mean']['CC_G_TTFB'],
                                                  df_stat_by_operator['50%']['TI_G_TTFB'],
                                                  df_stat_by_operator['75%']['TI_G_TTFB'],
                                                  df_stat_by_operator['mean']['TI_G_TTFB']))

print(" \t \t & DwnT & %.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_operator['50%']['BT_G_dt'],
                                                  df_stat_by_operator['75%']['BT_G_dt'], 
                                                  df_stat_by_operator['mean']['BT_G_dt'],
                                                  df_stat_by_operator['50%']['CC_G_dt'],
                                                  df_stat_by_operator['75%']['CC_G_dt'],
                                                  df_stat_by_operator['mean']['CC_G_dt'],
                                                  df_stat_by_operator['50%']['TI_G_dt'],
                                                  df_stat_by_operator['75%']['TI_G_dt'],
                                                  df_stat_by_operator['mean']['TI_G_dt']))

	\multirow{2}{*}{GGL} & TTFB & 41 & 101 & 108 & 67 & 86 & 75 & 70 & 96 & 89 \\
 	 	 & DwnT & 335 & 730& 1633 & 438 & 540 & 500 & 511 & 725 & 786 \\

In [20]:
## YouTube 
print("\t\multirow{2}{*}{YT} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_operator['50%']['BT_U_TTFB'],
                                                  df_stat_by_operator['75%']['BT_U_TTFB'],
                                                  df_stat_by_operator['mean']['BT_U_TTFB'],
                                                  df_stat_by_operator['50%']['CC_U_TTFB'],
                                                  df_stat_by_operator['75%']['CC_U_TTFB'],
                                                  df_stat_by_operator['mean']['CC_U_TTFB'],
                                                  df_stat_by_operator['50%']['TI_U_TTFB'],
                                                  df_stat_by_operator['75%']['TI_U_TTFB'],
                                                  df_stat_by_operator['mean']['TI_U_TTFB']))

print(" \t \t & DwnT & %.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f \\\ " 
                                                  %(df_stat_by_operator['50%']['BT_U_dt'],
                                                  df_stat_by_operator['75%']['BT_U_dt'], 
                                                  df_stat_by_operator['mean']['BT_U_dt'],
                                                  df_stat_by_operator['50%']['CC_U_dt'],
                                                  df_stat_by_operator['75%']['CC_U_dt'],
                                                  df_stat_by_operator['mean']['CC_U_dt'],
                                                  df_stat_by_operator['50%']['TI_U_dt'],
                                                  df_stat_by_operator['75%']['TI_U_dt'],
                                                  df_stat_by_operator['mean']['TI_U_dt']))

	\multirow{2}{*}{YT} & TTFB & 101 & 153 & 158 & 79 & 139 & 101 & 119 & 148 & 140 \\
 	 	 & DwnT & 475 & 947& 1571 & 537 & 661 & 608 & 642 & 935 & 916 \\

## Prepare for latex table  use  by  region and operator

In [21]:
## Facebook 
print("\multirow{2}{*}{Facebook} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f  \\\ " 
                                                  %(df_stat_by_region['50%']['eu_F_TTFB'],
                                                  #df_stat_by_region['75%']['eu_F_TTFB'],
                                                  df_stat_by_region['mean']['eu_F_TTFB'],
                                                  df_stat_by_region['50%']['us_ca_F_TTFB'],
                                                  #df_stat_by_region['75%']['us_ca_F_TTFB'],
                                                  df_stat_by_region['mean']['us_ca_F_TTFB'],
                                                  df_stat_by_region['50%']['others_F_TTFB'],
                                                  #df_stat_by_region['75%']['others_F_TTFB'],
                                                  df_stat_by_region['mean']['others_F_TTFB'],
                                                  df_stat_by_operator['50%']['BT_F_TTFB'],
                                                  #df_stat_by_operator['75%']['BT_F_TTFB'],
                                                  df_stat_by_operator['mean']['BT_F_TTFB'],
                                                  df_stat_by_operator['50%']['CC_F_TTFB'],
                                                  #df_stat_by_operator['75%']['CC_F_TTFB'],
                                                  df_stat_by_operator['mean']['CC_F_TTFB'],
                                                  df_stat_by_operator['50%']['TI_F_TTFB'],
                                                  #df_stat_by_operator['75%']['TI_F_TTFB'],
                                                  df_stat_by_operator['mean']['TI_F_TTFB']))

print(" \t & DwnT & \
%.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f& %.f  \\\ " 
                                                  %(df_stat_by_region['50%']['eu_F_dt'],
                                                  #df_stat_by_region['75%']['eu_F_dt'], 
                                                  df_stat_by_region['mean']['eu_F_dt'],
                                                  df_stat_by_region['50%']['us_ca_F_dt'],
                                                  #df_stat_by_region['75%']['us_ca_F_dt'],
                                                  df_stat_by_region['mean']['us_ca_F_dt'],
                                                  df_stat_by_region['50%']['others_F_dt'],
                                                  #df_stat_by_region['75%']['others_F_dt'],
                                                  df_stat_by_region['mean']['others_F_dt'],
                                                  df_stat_by_operator['50%']['BT_F_dt'],
                                                  #df_stat_by_operator['75%']['BT_F_dt'], 
                                                  df_stat_by_operator['mean']['BT_F_dt'],
                                                  df_stat_by_operator['50%']['CC_F_dt'],
                                                  #df_stat_by_operator['75%']['CC_F_dt'],
                                                  df_stat_by_operator['mean']['CC_F_dt'],
                                                  df_stat_by_operator['50%']['TI_F_dt'],
                                                  #df_stat_by_operator['75%']['TI_F_dt'],
                                                  df_stat_by_operator['mean']['TI_F_dt']))

print("\\hline")

## Google 
print("\multirow{2}{*}{Google} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f  \\\ " 
                                                  %(df_stat_by_region['50%']['eu_G_TTFB'],
                                                  #df_stat_by_region['75%']['eu_G_TTFB'],
                                                  df_stat_by_region['mean']['eu_G_TTFB'],
                                                  df_stat_by_region['50%']['us_ca_G_TTFB'],
                                                  #df_stat_by_region['75%']['us_ca_G_TTFB'],
                                                  df_stat_by_region['mean']['us_ca_G_TTFB'],
                                                  df_stat_by_region['50%']['others_G_TTFB'],
                                                  #df_stat_by_region['75%']['others_G_TTFB'],
                                                  df_stat_by_region['mean']['others_G_TTFB'],
                                                  df_stat_by_operator['50%']['BT_G_TTFB'],
                                                  #df_stat_by_operator['75%']['BT_G_TTFB'],
                                                  df_stat_by_operator['mean']['BT_G_TTFB'],
                                                  df_stat_by_operator['50%']['CC_G_TTFB'],
                                                  #df_stat_by_operator['75%']['CC_G_TTFB'],
                                                  df_stat_by_operator['mean']['CC_G_TTFB'],
                                                  df_stat_by_operator['50%']['TI_G_TTFB'],
                                                  #df_stat_by_operator['75%']['TI_G_TTFB'],
                                                  df_stat_by_operator['mean']['TI_G_TTFB']))

print(" \t & DwnT & \
%.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f& %.f  \\\ " 
                                                  %(df_stat_by_region['50%']['eu_G_dt'],
                                                  #df_stat_by_region['75%']['eu_G_dt'], 
                                                  df_stat_by_region['mean']['eu_G_dt'],
                                                  df_stat_by_region['50%']['us_ca_G_dt'],
                                                  #df_stat_by_region['75%']['us_ca_G_dt'],
                                                  df_stat_by_region['mean']['us_ca_G_dt'],
                                                  df_stat_by_region['50%']['others_G_dt'],
                                                  #df_stat_by_region['75%']['others_G_dt'],
                                                  df_stat_by_region['mean']['others_G_dt'],
                                                  df_stat_by_operator['50%']['BT_G_dt'],
                                                  #df_stat_by_operator['75%']['BT_G_dt'], 
                                                  df_stat_by_operator['mean']['BT_G_dt'],
                                                  df_stat_by_operator['50%']['CC_G_dt'],
                                                  #df_stat_by_operator['75%']['CC_G_dt'],
                                                  df_stat_by_operator['mean']['CC_G_dt'],
                                                  df_stat_by_operator['50%']['TI_G_dt'],
                                                  #df_stat_by_operator['75%']['TI_G_dt'],
                                                  df_stat_by_operator['mean']['TI_G_dt']))

print("\\hline")

            
## YouTube 
print("\multirow{2}{*}{YouTube} & TTFB & \
%.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f  \\\ " 
                                                  %(df_stat_by_region['50%']['eu_U_TTFB'],
                                                  #df_stat_by_region['75%']['eu_U_TTFB'],
                                                  df_stat_by_region['mean']['eu_U_TTFB'],
                                                  df_stat_by_region['50%']['us_ca_U_TTFB'],
                                                  #df_stat_by_region['75%']['us_ca_U_TTFB'],
                                                  df_stat_by_region['mean']['us_ca_U_TTFB'],
                                                  df_stat_by_region['50%']['others_U_TTFB'],
                                                  #df_stat_by_region['75%']['others_U_TTFB'],
                                                  df_stat_by_region['mean']['others_U_TTFB'],
                                                  df_stat_by_operator['50%']['BT_U_TTFB'],
                                                  #df_stat_by_operator['75%']['BT_U_TTFB'],
                                                  df_stat_by_operator['mean']['BT_U_TTFB'],
                                                  df_stat_by_operator['50%']['CC_U_TTFB'],
                                                  #df_stat_by_operator['75%']['CC_U_TTFB'],
                                                  df_stat_by_operator['mean']['CC_U_TTFB'],
                                                  df_stat_by_operator['50%']['TI_U_TTFB'],
                                                  #df_stat_by_operator['75%']['TI_U_TTFB'],
                                                  df_stat_by_operator['mean']['TI_U_TTFB']))

print(" \t & DwnT & \
%.f & %.f& %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f & %.f& %.f  \\\ " 
                                                  %(df_stat_by_region['50%']['eu_U_dt'],
                                                  #df_stat_by_region['75%']['eu_U_dt'], 
                                                  df_stat_by_region['mean']['eu_U_dt'],
                                                  df_stat_by_region['50%']['us_ca_U_dt'],
                                                  #df_stat_by_region['75%']['us_ca_U_dt'],
                                                  df_stat_by_region['mean']['us_ca_U_dt'],
                                                  df_stat_by_region['50%']['others_U_dt'],
                                                  #df_stat_by_region['75%']['others_U_dt'],
                                                  df_stat_by_region['mean']['others_U_dt'],
                                                  df_stat_by_operator['50%']['BT_U_dt'],
                                                  #df_stat_by_operator['75%']['BT_U_dt'], 
                                                  df_stat_by_operator['mean']['BT_U_dt'],
                                                  df_stat_by_operator['50%']['CC_U_dt'],
                                                  #df_stat_by_operator['75%']['CC_U_dt'],
                                                  df_stat_by_operator['mean']['CC_U_dt'],
                                                  df_stat_by_operator['50%']['TI_U_dt'],
                                                  #df_stat_by_operator['75%']['TI_U_dt'],
                                                  df_stat_by_operator['mean']['TI_U_dt']))

\multirow{2}{*}{Facebook} & TTFB & 153 & 222 & 141 & 209 & 540 & 626 & 114 & 152 & 121 & 202 & 135 & 149  \\
 	 & DwnT & 536 & 962& 523 & 654 & 2286 & 3244 & 385 & 1182 & 459 & 641 & 489& 563  \\
\hline
\multirow{2}{*}{Google} & TTFB & 55 & 78 & 70 & 93 & 191 & 177 & 41 & 108 & 67 & 75 & 70 & 89  \\
 	 & DwnT & 394 & 808& 460 & 645 & 1407 & 1610 & 335 & 1633 & 438 & 500 & 511& 786  \\
\hline
\multirow{2}{*}{YouTube} & TTFB & 117 & 142 & 82 & 118 & 230 & 253 & 101 & 158 & 79 & 101 & 119 & 140  \\
 	 & DwnT & 595 & 958& 585 & 743 & 1722 & 2068 & 475 & 1571 & 537 & 608 & 642& 916  \\